# code: language=Ansible insertSpaces=true tabSize=2
#
# Ansible playbook - `gates.yml`
# Manages the infrastructure access gates lifecycle.

- hosts:
    - gates

  vars:
    # Gates may be (re)created and theit host key will chnage.
    # The role 'system_sshd' deploy the correct keys.
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:

    - include_role:
        name: system_ansible
      tags: [always, system_ansible]

    - include_role:
        name: system_sshd
      tags: [always, system_sshd]

    - include_role:
        name: system_fail2ban
      tags: [always, system_fail2ban]

    - include_role:
        name: system_autoupdate
      tags: [always, system_autoupdate]
